name: Angels
favicon: null
layout_spectrum: 0.86241
typography_spectrum: 0.9065880563575774
title: Angels
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.788677427219227
purpose: []
